# Generated by Django 4.2.1 on 2023-06-06 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                ("firstname", models.CharField(db_index=True, max_length=255)),
                ("lastname", models.CharField(db_index=True, max_length=255)),
                ("phone", models.CharField(max_length=15, null=True, unique=True)),
                ("gender", models.CharField(max_length=67)),
                ("address", models.TextField()),
                ("city", models.CharField(db_index=True, max_length=255)),
                ("state", models.CharField(db_index=True, max_length=255)),
                ("postal_code", models.CharField(db_index=True, max_length=255)),
                ("country", models.CharField(db_index=True, max_length=255)),
                (
                    "profile_image",
                    models.ImageField(default="user.png", upload_to="profile/"),
                ),
                ("user_type", models.CharField(default=1, max_length=1)),
                ("name", models.CharField(max_length=200)),
                ("tc", models.BooleanField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployerAdmin",
            fields=[
                (
                    "employer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app_user.employer",
                    ),
                ),
            ],
            bases=("app_user.employer",),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "employer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app_user.employer",
                    ),
                ),
            ],
            bases=("app_user.employer",),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
